### ISSUE TITLE
Problem Authenticating Facebook From R

### ISSUE THREAD

**Issue by upchair** [pablobarbera/Rfacebook#32] opened 2015-05-23 15:22 UTC
Please when I use rfacebook authentication in trying to connect to facebook from R I get this error message

Invalid Scopes: friends_birthday, friends_hometown, friends_location, friends_relationships, user_checkins, friends_status, friends_checkins, friends_likes, export_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

Please could you please explain what the problem is. Initially I was able to log in with no problem.  I suspect this problem started after the facebook graph API was upgraded to Version 2. I may be wrong. Julain from the Think To Start forum suspects it maybe a bug in the rfacebook package. As a result, he directed me to you.

I hope you can resolve it cause I need to pull some data from facebook into R.

Thank you

Richard

**Comment by pablobarbera** [comment] 2015-05-23 15:54
This should be fixed in the latest version of Rfacebook on github (not on CRAN yet). Can you re-install from here and see if that solves the problem? If not, creating the token with extended_permissions=FALSE should work with the CRAN version. Thanks!






On Saturday, May 23, 2015 at 11:22 AM, upchair <notifications@github.com>, wrote:

Please when I use rfacebook authentication in trying to connect to facebook from R I get this error message


Invalid Scopes: friends_birthday, friends_hometown, friends_location, friends_relationships, user_checkins, friends_status, friends_checkins, friends_likes, export_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions


Please could you please explain what the problem is. Initially I was able to log in with no problem.  I suspect this problem started after the facebook graph API was upgraded to Version 2. I may be wrong. Julain from the Think To Start forum suspects it maybe a bug in the rfacebook package. As a result, he directed me to you.


I hope you can resolve it cause I need to pull some data from facebook into R.


Thank you


Richard

**Comment by upchair** [comment] 2015-05-24 10:01
Pablo I did as you instructed. When I changes the extended permissions parameter from true to false in my script it worked. Thanks a lot.

Please when are you likely to update the Rfacebook package  to the latest version in CRAN so I can update it from there. 

Thanks

Richard

**Comment by caiomsouza** [comment] 2015-07-11 21:05
It worked for me.

1) I changed from extended_permissions = TRUE to extended_permissions = FALSE

fb_oauth <- fbOAuth(app_id="XXXXX", app_secret="YYYYYY",extended_permissions = FALSE)

2) Put http://localhost:1410 on my Facebook App

3) Use the option 2.

The output is:

When done, press any key to continue...
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 2
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Error in as.character(tools:::httpdPort) : 
  cannot coerce type 'closure' to vector of type 'character'
Authentication complete.
Error: Deprecated: supply token object to config directly

**Comment by caiomsouza** [comment] 2015-07-11 21:08
Richard,

Maybe the code below is your answer for your question "Please could you direct me to where I can install the latest rfacebook package update here on github".

```r
install.packages("devtools")
library(devtools)
install_github("Rfacebook", "pablobarbera", subdir="Rfacebook")
```

**Closed** 2015-08-06 21:12 UTC
